### ISSUE TITLE
aoinit error

### ISSUE THREAD

**Issue by danmoser** [frigaut/yao#15]
When I try to run any of the examples, I the this error:

 Warning: Can't export FFTW wisdom to $USER/.yorick/fftw_wisdom_file.dat
ERROR (sh_wfs) _shwfs_spots2slopes takes exactly 22 arguments
  LINE: 1090  FILE: /path/to/yao/yao_wfs.i

**Comment by frigaut** [comment]
Hi Daniel,

Perhaps you don’t have a ~/.yorick directory?
On what platform are you running yao?
Cheers,
Francois

**Comment by danmoser** [comment]
Dear Francois,
I'm using Ubuntu 16.04. The yao from apt (v 5.4.0) works fine (I have the ~/.yorick dir), but with this one (v 5.10.4) I get this error. My yorick is v2.2.04.

**Comment by frigaut** [comment]
Do you have a ~/.yorick/fftw_wisdom_file.dat already existing? May be it belongs to another user, or i snot writable? Trying deleting it if another one is already there.
F

**Comment by danmoser** [comment]
I had the file, but I deleted it and created a new one with "init_fftw_wisdom". Same problem...

**Comment by frigaut** [comment]
Oh, sorry, I should have read the initial error message more carefully. In addition to the fftw_wisdom *warning*, the error is triggered by a mismatch between yao versions, as indicated in the error message:
ERROR (sh_wfs) _shwfs_spots2slopes takes exactly 22 arguments
LINE: 1090 FILE: /path/to/yao/yao_wfs.i

Do you have any of your own code that would make use of _shwfs_spots2slopes?
How did you install the latest yao version (5.10.4)? With the ubuntu package manager?
if not, then something is astray with the ubuntu packages, and I suggest you may re-install yao from github.

* install git with apt-get
* make sure you have the ubuntu build environment (make, gcc etc)
* make sure you have the yorick dev package
Then, in a terminal:
git clone https://github.com/frigaut/yao.git <https://github.com/frigaut/yao.git>
cd yao
yorick -batch make.i
make clean
make
[sudo] make install  (I believe ubuntu install stuff as root, so you’ll need the sudo here).
make check  (to check it’s working).

I hope this will solve the problem.
Francois

**Comment by danmoser** [comment]
Dear Francois,
I did as you told, and no good. I get this error with any of the yao examples.
Something I noticed is that _shwfs_spots2slopes at "yao_wfs.i" has 22 arguments, but at "yao_fast.c" (line 1111) it is defined with 23. The extra one is the _binxy2_ (line 1116). 
May it be the source of the problem?

**Comment by frigaut** [comment]
yes, that’s exactly why I was directing you to install yao directly from github; which obviously didn’t work, because otherwise your new version would have 23 arguments to _shwfs_spots2slopes in yao_wfs.i.
If you followed my directions to install yao, then the only explanation I see is that your install is picking up another yao_wfs.i (and probably yao.i) from somewhere else in your system.

There are some diagnostics printed out what you start yao. Can you join the full text of starting yao from a terminal:
yorick -i yao.i

and then within yao, all instructions and printout that lead to your problem. Run an yao example for instance.
Thanks, I think we’re close.
Francois

**Comment by danmoser** [comment]
Francois,
I believe the source of the problem is the /usr/lib/yorick/lib/**yao.so** file.
When the file compiled from git is used in this path, I get the following (I'm sure this is not a permission problem):

`` Yao version 5.10.4, Last modified 2018feb19 ``
 ``Found and included yao.conf in /home/$USER/.yorick/``
``ERROR (*main*) plug_in: unable to find dynamic library file``
``WARNING detailed line number information unavailable``
``now at pc= 1 (of 11), failed at pc= 5``
`` LINE: 50  FILE: /usr/lib/yorick/i/yao.i ``

When I use the yao.so from Ubuntu package:

`` Yao version 5.10.4, Last modified 2018feb19``
`` Found and included yao.conf in /home/moser/.yorick/ ``
`` System-wide configuration for the pkg_mngr loaded. `` 
`` Local Y_HOME tree: /usr/local/lib/yorick/ ``
`` Local Y_SITE tree: /usr/local/lib/yorick/ ``

Then, when I try to run an example:

``NGS#1 flux varies between 433 and 599 photon/subap/it``
``ERROR (sh_wfs) _shwfs_spots2slopes takes exactly 22 arguments``
``  LINE: 1090  FILE: /usr/lib/yorick/i/yao_wfs.i``

**Comment by danmoser** [comment]
Francois, any news on this?

**Comment by mvandam** [comment]
It appears that you have not installed yao properly. When you do:
yorick -batch make.i
make
sudo make install

do you have any error messages? You might want to make sure you have yorick-dev installed first. 
sudo apt install yorick-dev.

**Comment by danmoser** [comment]
No error in these cmds. Only in execution (above). Here is my output:

``` bash 
$ make clean
rm -f *~ '#'* core* *.core a.out yinit.* ywrap.* *.dep so_locations Make.tmp
rm -f Y_HOME.txt
rm -f aoSimulUtils.o yao_fast.o utils.o yorick libyao.a yao.so yao.def 
$
$ yorick -batch make.i
updated ./Makefile
$
$ make
cc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -fPIC -DPLUG_IN -I. -I/usr/lib/yorick/include   -c -o aoSimulUtils.o aoSimulUtils.c
cc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -fPIC -DPLUG_IN -I. -I/usr/lib/yorick/include   -c -o yao_fast.o yao_fast.c
cc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -fPIC -DPLUG_IN -I. -I/usr/lib/yorick/include   -c -o utils.o utils.c
/usr/lib/yorick/lib/codger w yao   yao.i
found yao.i in current directory
cc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -fPIC -DPLUG_IN -I. -I/usr/lib/yorick/include   -c -o ywrap.o ywrap.c
cc -g -O2 -Wl,-Bsymbolic-functions -Wl,-z,relro  -fPIC -shared -o yao.so aoSimulUtils.o yao_fast.o utils.o ywrap.o  -lm 
$
$ sudo make install
/usr/lib/yorick/lib/install.sh `cat /usr/lib/yorick/lib/install.grp` yao.so /usr/lib/yorick/lib
/usr/lib/yorick/lib/install.sh `cat /usr/lib/yorick/lib/install.grp` yao.i /usr/lib/yorick/i0
if test -n ""; then /usr/lib/yorick/lib/install.sh `cat /usr/lib/yorick/lib/install.grp`  /usr/lib/yorick/i-start; fi
if test -n ""; then /usr/lib/yorick/lib/install.sh `cat /usr/lib/yorick/lib/install.grp`  /usr/lib/yorick/i; fi
if test -f "yao.cfg"; then /usr/lib/yorick/lib/install.sh `cat /usr/lib/yorick/lib/install.grp` yao.cfg /usr/lib/yorick/lib; fi
$
```

**Comment by mvandam** [comment]
On Ubuntu, I see -lfftw3f:

cc -g -O2 -Wl,-Bsymbolic-functions -Wl,-z,relro -L/opt/local/lib -fPIC -shared -o yao.so aoSimulUtils.o utils.o yao_fast.o ywrap.o -lfftw3f -lm 

Have you installed fftw3 and fftw3-dev? 
sudo apt install fftw3
sudo apt install fftw3-dev

**Comment by frigaut** [comment]
correct. however, if fftw3 was not installed, it should throw an error at link time. 

And I believe the dependency is actually on libfftw3-single3
https://packages.ubuntu.com/search?keywords=fftw3 <https://packages.ubuntu.com/search?keywords=fftw3>
and 
https://packages.ubuntu.com/xenial/math/yorick-yao <https://packages.ubuntu.com/xenial/math/yorick-yao>

**Comment by danmoser** [comment]
The directory I built yao is from github. And I also had the _libfftw3-dev_ and _fftw3-dev_ installed.
Here is my Makefile:
```
# these values filled in by    yorick -batch make.i
Y_MAKEDIR=/usr/lib/yorick
Y_EXE=/usr/lib/yorick/bin/yorick
Y_EXE_PKGS=
Y_EXE_HOME=/usr/lib/yorick
Y_EXE_SITE=/usr/lib/yorick
Y_HOME_PKG=

# ----------------------------------------------------- optimization flags

# options for make command line, e.g.-   make COPT=-g TGT=exe
COPT=$(COPT_DEFAULT)
TGT=$(DEFAULT_TGT)

# ------------------------------------------------ macros for this package

PKG_NAME=yao
PKG_I=yao.i

OBJS=aoSimulUtils.o yao_fast.o utils.o

# change to give the executable a name other than yorick
PKG_EXENAME=yorick

# PKG_DEPLIBS=-Lsomedir -lsomelib   for dependencies of this package
PKG_DEPLIBS=
# set compiler (or rarely loader) flags specific to this package
PKG_CFLAGS=
PKG_LDFLAGS=

# list of additional package names you want in PKG_EXENAME
# (typically $(Y_EXE_PKGS) should be first here)
EXTRA_PKGS=$(Y_EXE_PKGS)

# list of additional files for clean
PKG_CLEAN=

# autoload file for this package, if any
PKG_I_START=
# non-pkg.i include files for this package, if any
PKG_I_EXTRA=

# -------------------------------- standard targets and rules (in Makepkg)

# set macros Makepkg uses in target and dependency names
# DLL_TARGETS, LIB_TARGETS, EXE_TARGETS
# are any additional targets (defined below) prerequisite to
# the plugin library, archive library, and executable, respectively
PKG_I_DEPS=$(PKG_I)
Y_DISTMAKE=distmake

include $(Y_MAKEDIR)/Make.cfg
include $(Y_MAKEDIR)/Makepkg
include $(Y_MAKEDIR)/Make$(TGT)

# override macros Makepkg sets for rules and other macros
# see comments in Y_HOME/Makepkg for a list of possibilities

# if this package built with mpy: 1. be sure mpy appears in EXTRA_PKGS,
# 2. set TGT=exe, and 3. uncomment following two lines
# Y_MAIN_O=$(Y_LIBEXE)/mpymain.o
# include $(Y_MAKEDIR)/Makempy

# configure script for this package may produce make macros:
# include output-makefile-from-package-configure

# reduce chance of yorick-1.5 corrupting this Makefile
MAKE_TEMPLATE = protect-against-1.5

# ------------------------------------- targets and rules for this package

# simple example:
#myfunc.o: myapi.h
# more complex example (also consider using PKG_CFLAGS above):
#myfunc.o: myapi.h myfunc.c
#	$(CC) $(CPPFLAGS) $(CFLAGS) -DMY_SWITCH -o $@ -c myfunc.c

# -------------------------------------------------------- end of Makefile
```

**Comment by danmoser** [comment]
It worked!!! I did not change anything. It correctly got _PKG_DEPLIBS_STATIC=-lm /usr/lib/libfftw3f.a_

Many thanks!

**Comment by frigaut** [comment]
yeah, sorry it took so long.
Have fun running yao.  What do you want to use it for?
Francois

**Comment by danmoser** [comment]
Francois,
I'm closing the issue and replying the usage in your e-mail.
