### ISSUE TITLE
How can l save PSF data as fits file by using YAO

### ISSUE THREAD

**Issue by mrainezty** [frigaut/yao#18]

**Comment by mvandam** [comment]
The file containing the PSFs is automatically saved at the end of the simulation. 
They are saved as parprefix+"-imav.fits"
Please read the manual, as it has a lot of useful information!

**Comment by mrainezty** [comment]
> The file containing the PSFs is automatically saved at the end of the simulation.
> They are saved as parprefix+"-imav.fits"
> Please read the manual, as it has a lot of useful information!

thank you very much
