### ISSUE TITLE
How can l set the observation target??

### ISSUE THREAD

**Issue by mrainezty** [frigaut/yao#19]
Dear developer

    l have read the manual document which introduce the features of YAO, now l have already determined the parameters of my AO system, how can l set the observation target? For example, l want to simulate observation of a galaxy, how to set the number and location of stars and planets???  
  
best
PHD T.Y

**Comment by mvandam** [comment]
Set the parameters target.xposition and target.yposition. This will produce a PSF at locations in the field that you specify. You then convolve the PSF by your science field (multiple stars or a galaxy).

**Comment by mrainezty** [comment]
> Set the parameters target.xposition and target.yposition. This will produce a PSF at locations in the field that you specify. You then convolve the PSF by your science field (multiple stars or a galaxy).

That means if l want to observe specific stars or planet, l need to use other software to change the PSF .fits file? l can not set the specific target in YAO?
