### ISSUE TITLE
what's the observe target of example 6*6LGS.par?

### ISSUE THREAD

**Issue by mrainezty** [frigaut/yao#20]
Dear developer

Point spread function describes the response of the  AO system to a point source or target. l run the example(6*6LGS.par ) presented by YAO, and l got the corresponding psf file(.fits file). But what's the corresponding target of this example which is the point source of the AO system? Now, l want to observe the sun, can l set the sun as the target in YAO? 

best

**Comment by mvandam** [comment]
The PSF is calculated at the location target.xlocation, target.ylocation for a point source (e.g., an unresolved star). You will have to convolve this by the science target. The sun is very extended so the PSF will vary across the sun. For a small region (say 5" by 5"), you can convolve the PSF from YAO by the true image to find what the image would look like. I will not be answering any more questions on how to do this as I have other work to do!
