### ISSUE TITLE
Multi targets setting for simulating star and exoplanet

### ISSUE THREAD

**Issue by mrainezty** [frigaut/yao#24]
Dear Developer:
  l am using YAO v5.4.0 with ubuntu 64 emulated in a virtual machine on my windows system.
l ran the example mad_maco_star. After that l found that multi targets are set into different fits files.
  In order to simulate the real data, we want to set one fixed star and one exoplanet in one field. At the time , those two targets should be output to one fits file(we try to use the fixed star as NGS, and set the exoplanet as target). l have read the source code and example you provided, l can't confirm that whether Yao can simulate the case l said above. 

Thank you very much!

**Comment by mvandam** [comment]
If you want to save the PSF of any location on the field, just add it to the target data structure: target.xposition and target.yposition

You can use this to set the location of the star and the planet, but they are likely to have the same PSF
