### ISSUE TITLE
NGS setting and output

### ISSUE THREAD

**Issue by mrainezty** [frigaut/yao#25]
We are using YAO to stimulate the correction of AO system( YAO v5.4.0 with ubuntu 64 emulated in a virtual machine on windows system). 
 l found some result in ~/.yorick/yao/  .  We want to confirm that file named '-imav.fits'  is the fits file which contains the target star?  we found that the optical quality of -imav fits is better than what we saw in Instantaneous PSFs in GUI.  At the same time , we can't see the guide star in fits file. The NGS is  just a red cross in GUI. we want to know that can we output the fits file contain the NGS ? 
Thank you very much!

**Comment by mvandam** [comment]
The PSF on the guide star is not saved. If you want to save the PSF of any location on the field, just add it to the target data structure: target.xposition and target.yposition

The quantity imav is saved as *imav.fits"
yao_fitswrite,YAO_SAVEPATH+parprefix+"-imav.fits",imav, header;

In the future, please read the documentation and look at the code.
